import os

# বর্তমান ডিরেক্টরিতেই ফাইলগুলো তৈরি হবে
base_dir = "."

# File Contents
files = {
    "package.json": r"""{
  "name": "return-in-islam-foundation",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@supabase/supabase-js": "^2.33.0",
    "@stripe/stripe-js": "^1.45.0",
    "autoprefixer": "^10.4.14",
    "next": "14.3.1",
    "next-translate": "^1.4.0",
    "postcss": "^8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "stripe": "^11.12.0",
    "tailwindcss": "^3.5.2"
  }
}""",

    "next.config.js": r"""const nextTranslate = require('next-translate')
module.exports = nextTranslate({
  reactStrictMode: true,
})""",

    "i18n.json": r"""{
  "locales": ["bn", "en"],
  "defaultLocale": "bn",
  "pages": {
    "*": ["common"]
  }
}""",

    "tailwind.config.js": r"""module.exports = {
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}"
  ],
  theme: {
    extend: {}
  },
  plugins: []
}""",

    "postcss.config.js": r"""module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
}""",

    ".gitignore": r"""node_modules
.next
.env.local
.env.development.local
.env.production.local
.DS_Store""",

    ".env.example": r"""# Client (public)
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=public-anon-key
NEXT_PUBLIC_BASE_URL=http://localhost:3000
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...

# Server (do NOT commit; add these in your hosting environment)
SUPABASE_SERVICE_ROLE_KEY=service-role-key
STRIPE_SECRET_KEY=sk_test_...""",

    "README.md": r"""# Return in Islam Foundation — Full Site Starter

Features:
- Next.js + TailwindCSS
- next-translate (bn default, en)
- Supabase: Auth, Storage, DB (client + admin service role)
- Stripe Checkout server integration (server secret required)
- Full e-commerce: product grid, product detail, cart, wishlist, reviews, search, filters, pagination
- Admin: product CRUD, article CRUD, image upload to Supabase Storage
- Pages: /, /articles, /donate, /prayer-times, /about, /quran, /dowa, /hadith, /shop, /cart, /checkout, /admin

Setup:
1. Copy `.env.example` to `.env.local` and fill values. Do NOT put service role or stripe secret in git.
2. Install deps:
   npm install
3. Seed Supabase:
   - Create a Supabase project.
   - In Supabase SQL editor paste `supabase/schema-and-seed.sql` and run.
   - Create a storage bucket named `products` (public or with appropriate rules) if using Storage.
4. Run dev:
   npm run dev
5. Admin:
   - Create account via /auth/signup.
   - Login via /auth/login then visit /admin/products to create/edit products.
6. Stripe:
   - Add STRIPE_SECRET_KEY to server env and NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY to .env.local for client.

Security:
- Never commit SUPABASE_SERVICE_ROLE_KEY or STRIPE_SECRET_KEY.
- Use server-side environment variables for admin APIs.""",

    "supabase/schema-and-seed.sql": r"""-- Schema + seed for products, product_translations, categories, reviews, quran/duas/hadiths, slider_items

create table if not exists categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  sku text unique,
  price integer not null, -- price in smallest currency unit (paisa)
  currency text default 'BDT',
  stock integer default 100,
  created_at timestamptz default now()
);

create table if not exists product_translations (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  locale text not null,
  title text,
  description text,
  slug text,
  image_url text,
  category_id bigint references categories(id)
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  locale text not null,
  rating integer,
  content text,
  author text,
  created_at timestamptz default now()
);

-- Additional tables for site content (articles, duas, hadiths, quran_verses, slider)
create table if not exists articles (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  locale text not null,
  title text not null,
  excerpt text,
  body text,
  created_at timestamptz default now()
);

create table if not exists duas (
  id bigint generated by default as identity primary key,
  locale text not null,
  title text,
  arabic text,
  translation text,
  created_at timestamptz default now()
);

create table if not exists hadiths (
  id bigint generated by default as identity primary key,
  locale text not null,
  title text,
  text text,
  source text,
  created_at timestamptz default now()
);

create table if not exists quran_verses (
  id bigint generated by default as identity primary key,
  surah integer,
  ayah integer,
  arabic text,
  translation text,
  locale text not null default 'bn',
  created_at timestamptz default now()
);

create table if not exists slider_items (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  image_url text,
  link text,
  locale text not null default 'bn',
  created_at timestamptz default now()
);

-- seed categories
insert into categories (slug, name) values
('books','Books'),
('clothing','Clothing'),
('electronics','Electronics'),
('home','Home & Kitchen');

-- seed 20 products with bn and en translations and placeholder images
insert into products (sku, price, currency, stock) values
('SKU-001', 19900, 'BDT', 50),
('SKU-002', 35000, 'BDT', 20),
('SKU-003', 4500, 'BDT', 150),
('SKU-004', 129900, 'BDT', 10),
('SKU-005', 29900, 'BDT', 25),
('SKU-006', 8990, 'BDT', 80),
('SKU-007', 159000, 'BDT', 5),
('SKU-008', 45000, 'BDT', 12),
('SKU-009', 12500, 'BDT', 60),
('SKU-010', 7999, 'BDT', 200);

-- bn translations
insert into product_translations (product_id, locale, title, description, slug, image_url, category_id)
values
(1,'bn','কিতাব: ইসলামী শিক্ষা','একটি ক্লাসিক ইসলামিক বই।','kitab-islami-shikkha','https://picsum.photos/seed/p1/800/600',1),
(2,'bn','কাপড়: কুর্তা','আরামদায়ক কুর্তা।','kurta','https://picsum.photos/seed/p2/800/600',2),
(3,'bn','ইলেকট্রনিক: হেডফোন','উচ্চমানের সঙ্গীত অভিজ্ঞতা।','headphone','https://picsum.photos/seed/p3/800/600',3),
(4,'bn','বাড়ি: প্রেয়ার রগ','নিরাপদ ও আরামদায়ক।','prayer-rug','https://picsum.photos/seed/p4/800/600',4),
(5,'bn','কিতাব: কোরআন শিক্ষা','শিশুদের জন্য কোরআন শিক্ষা।','quran-kids','https://picsum.photos/seed/p5/800/600',1),
(6,'bn','গয়না: আনক','স্টাইলিশ আনক।','anok','https://picsum.photos/seed/p6/800/600',2),
(7,'bn','ইলেকট্রনিক: স্মার্টওয়াচ','ফিটনেস ট্র্যাকিং সহ স্মার্টওয়াচ।','smartwatch','https://picsum.photos/seed/p7/800/600',3),
(8,'bn','বাড়ি: ল্যাম্প','স্টাইলিশ ল্যাম্প।','lamp','https://picsum.photos/seed/p8/800/600',4),
(9,'bn','কফি মিক্সার','দৈনন্দিন ব্যবহার উপযোগী।','coffee-mixer','https://picsum.photos/seed/p9/800/600',4),
(10,'bn','ঘড়ি: ওয়াচ','একটি ক্লাসিক হাতঘড়ি।','watch','https://picsum.photos/seed/p10/800/600',2);

-- en translations
insert into product_translations (product_id, locale, title, description, slug, image_url, category_id)
values
(1,'en','Book: Islamic Education','A classic Islamic education book.','book-islamic-education','https://picsum.photos/seed/p1/800/600',1),
(2,'en','Clothing: Kurta','Comfortable kurta.','kurta','https://picsum.photos/seed/p2/800/600',2),
(3,'en','Electronics: Headphones','High quality listening experience.','headphone','https://picsum.photos/seed/p3/800/600',3),
(4,'en','Home: Prayer Rug','Safe and comfortable.','prayer-rug','https://picsum.photos/seed/p4/800/600',4),
(5,'en','Book: Quran for Kids','Quran learning for kids.','quran-kids','https://picsum.photos/seed/p5/800/600',1),
(6,'en','Jewelry: Anok','Stylish anok.','anok','https://picsum.photos/seed/p6/800/600',2),
(7,'en','Electronics: Smartwatch','Smartwatch with fitness tracking.','smartwatch','https://picsum.photos/seed/p7/800/600',3),
(8,'en','Home: Lamp','Stylish lamp.','lamp','https://picsum.photos/seed/p8/800/600',4),
(9,'en','Coffee Mixer','Ideal for daily use.','coffee-mixer','https://picsum.photos/seed/p9/800/600',4),
(10,'en','Watch: Classic','A classic wristwatch.','watch','https://picsum.photos/seed/p10/800/600',2);

-- sample articles, duas, hadiths, quran verses, slider
insert into articles (slug, locale, title, excerpt, body)
values
('welcome','bn','পরিচয়','আমাদের মিশন সম্পর্কে সংক্ষিপ্ত পরিচিতি।','এটি বাংলায় একটি নমুনা নিবন্ধ।'),
('welcome','en','An Introduction','A brief introduction to our mission.','This is a sample article.');

insert into duas (locale, title, arabic, translation)
values ('bn','দুয়ার নমুনা','اَللّٰهُمَّ اهْدِنَا','হে আল্লাহ, আমাদের সঠিক পথ দেখান।'),
       ('en','Sample Dua','اَللّٰهُمَّ اهْدِنَا','O Allah, guide us.');

insert into hadiths (locale, title, text, source)
values ('bn','উদাহরণ হাদিস','নির্ভরযোগ্যতা একটি গুণ।','Sahih'),
       ('en','Sample Hadith','Being truthful is a virtue.','Sahih');

insert into quran_verses (surah, ayah, arabic, translation, locale)
values (1,1,'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ','In the name of Allah, the Most Gracious, the Most Merciful.','bn'),
       (1,1,'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ','In the name of Allah, the Most Gracious, the Most Merciful.','en');

insert into slider_items (title, subtitle, image_url, link, locale)
values ('স্বাগতম','আমাদের সাথে যুক্ত হোন','https://picsum.photos/seed/slide1/1200/400','/articles/welcome','bn'),
       ('Welcome','Join the foundation','https://picsum.photos/seed/slide2/1200/400','/articles/welcome','en');""",

    "lib/supabaseClient.js": r"""import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''

export const supabase = createClient(supabaseUrl, supabaseAnonKey)""",

    "lib/supabaseAdmin.js": r"""import { createClient } from '@supabase/supabase-js'

const url = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
const serviceRole = process.env.SUPABASE_SERVICE_ROLE_KEY || ''

export const supabaseAdmin = createClient(url, serviceRole)

export default supabaseAdmin""",

    "styles/globals.css": r"""@tailwind base;
@tailwind components;
@tailwind utilities;

body { @apply bg-white text-gray-900 antialiased; }""",

    "pages/_app.js": r"""import '../styles/globals.css'
import Layout from '../components/Layout'
import { CartProvider } from '../lib/cart'
import 'react-toastify/dist/ReactToastify.css'

export default function MyApp({ Component, pageProps }) {
  return (
    <CartProvider>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </CartProvider>
  )
}""",

    "lib/cart.js": r"""import { createContext, useContext, useEffect, useState } from 'react'

const CartContext = createContext()

export function CartProvider({ children }) {
  const [cart, setCart] = useState({ items: [] })
  useEffect(() => {
    const raw = localStorage.getItem('cart_v1')
    if (raw) setCart(JSON.parse(raw))
  }, [])
  useEffect(() => {
    localStorage.setItem('cart_v1', JSON.stringify(cart))
  }, [cart])

  const addItem = (product, qty = 1) => {
    setCart(prev => {
      const found = prev.items.find(i => i.productId === product.id)
      if (found) {
        return { items: prev.items.map(i => i.productId === product.id ? { ...i, qty: i.qty + qty } : i) }
      }
      return { items: [...prev.items, { productId: product.id, title: product.title, price: product.price, image: product.image_url, qty }] }
    })
  }

  const updateQty = (productId, qty) => setCart(prev => ({ items: prev.items.map(i => i.productId === productId ? { ...i, qty } : i) }))
  const removeItem = (productId) => setCart(prev => ({ items: prev.items.filter(i => i.productId !== productId) }))
  const clear = () => setCart({ items: [] })
  const total = () => cart.items.reduce((s, i) => s + (i.price * i.qty), 0)

  return (
    <CartContext.Provider value={{ cart, addItem, updateQty, removeItem, clear, total }}>
      {children}
    </CartContext.Provider>
  )
}

export const useCart = () => useContext(CartContext)""",

    "components/Layout.jsx": r"""import NavBar from './NavBar'
import Footer from './Footer'

export default function Layout({ children }) {
  return (
    <div className="min-h-screen flex flex-col">
      <NavBar />
      <main className="flex-1 container mx-auto px-4 py-8">{children}</main>
      <Footer />
    </div>
  )
}""",

    "components/NavBar.jsx": r"""import Link from 'next/link'
import useTranslation from 'next-translate/useTranslation'
import LanguageSwitcher from './LanguageSwitcher'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'

export default function NavBar() {
  const { t } = useTranslation('common')
  const [user, setUser] = useState(null)

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => setUser(data.user || null))
    const { data: sub } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user || null)
    })
    return () => sub?.subscription?.unsubscribe?.()
  }, [])

  return (
    <nav className="bg-indigo-600 text-white">
      <div className="container mx-auto px-4 py-3 flex items-center justify-between">
        <Link href="/">
          <a className="font-semibold text-lg">{t('siteTitle')}</a>
        </Link>
        <div className="flex items-center space-x-4">
          <Link href="/"><a className="hover:underline">{t('nav.home')}</a></Link>
          <Link href="/articles"><a className="hover:underline">{t('nav.articles')}</a></Link>
          <Link href="/shop"><a className="hover:underline">{t('nav.shop')}</a></Link>
          <Link href="/prayer-times"><a className="hover:underline">{t('nav.prayerTimes')}</a></Link>
          <Link href="/donate"><a className="hover:underline">{t('nav.donate')}</a></Link>
          <Link href="/quran"><a className="hover:underline">{t('nav.quran')}</a></Link>
          <Link href="/dowa"><a className="hover:underline">{t('nav.dua')}</a></Link>
          <Link href="/hadith"><a className="hover:underline">{t('nav.hadith')}</a></Link>
          <Link href="/cart"><a className="hover:underline">{t('nav.cart')}</a></Link>
          <LanguageSwitcher />
          {user ? <Link href="/admin"><a className="ml-2 bg-white text-indigo-600 px-2 py-1 rounded">{t('nav.admin')}</a></Link> :
            <Link href="/auth/login"><a className="ml-2 bg-white text-indigo-600 px-2 py-1 rounded">{t('auth.login')}</a></Link>}
        </div>
      </div>
    </nav>
  )
}""",

    "components/LanguageSwitcher.jsx": r"""import { useRouter } from 'next/router'

export default function LanguageSwitcher() {
  const router = useRouter()
  const { locale, locales, pathname, asPath, query } = router
  return (
    <div className="flex items-center space-x-1">
      {locales.map((l) => (
        <button
          key={l}
          onClick={() => router.push({ pathname, query }, asPath, { locale: l })}
          className={`px-2 py-1 rounded ${locale === l ? 'bg-white text-indigo-600' : 'bg-indigo-500 text-white'}`}
          aria-pressed={locale === l}
        >
          {l === 'bn' ? 'বাংলা' : 'EN'}
        </button>
      ))}
    </div>
  )
}""",

    "components/Footer.jsx": r"""import useTranslation from 'next-translate/useTranslation'

export default function Footer() {
  const { t } = useTranslation('common')
  return (
    <footer className="bg-gray-100 text-gray-700">
      <div className="container mx-auto px-4 py-6 text-center">
        <p>{t('footer.copy')}</p>
      </div>
    </footer>
  )
}""",

    "components/Slider.jsx": r"""import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'

export default function Slider({ items = [], interval = 5000 }) {
  const [index, setIndex] = useState(0)
  const timerRef = useRef(null)

  useEffect(() => {
    if (!items.length) return
    timerRef.current = setInterval(() => setIndex(i => (i + 1) % items.length), interval)
    return () => clearInterval(timerRef.current)
  }, [items, interval])

  if (!items.length) return null

  return (
    <div className="relative overflow-hidden rounded shadow-sm">
      {items.map((it, i) => (
        <div
          key={i}
          className={`transition-opacity duration-700 absolute inset-0 ${i === index ? 'opacity-100' : 'opacity-0 pointer-events-none'}`}
        >
          <div className="h-64 md:h-80 bg-cover bg-center flex items-center justify-center" style={{ backgroundImage: `url(${it.image_url || '/default-slide.jpg'})` }}>
            <div className="bg-black/40 text-white p-6 rounded">
              <div className="text-2xl font-bold">{it.title}</div>
              {it.subtitle && <div className="mt-2">{it.subtitle}</div>}
              {it.link && <Link href={it.link}><a className="inline-block mt-3 bg-white text-indigo-600 px-3 py-1 rounded">Read</a></Link>}
            </div>
          </div>
        </div>
      ))}
      <div className="absolute bottom-3 left-1/2 transform -translate-x-1/2 flex space-x-2">
        {items.map((_, i) => (
          <button key={i} onClick={() => setIndex(i)} className={`w-2 h-2 rounded-full ${i === index ? 'bg-white' : 'bg-white/50'}`}></button>
        ))}
      </div>
    </div>
  )
}""",

    "components/ProductCard.jsx": r"""import Link from 'next/link'

export default function ProductCard({ p }) {
  return (
    <div className="border rounded p-3">
      <Link href={`/shop/${p.slug}`}>
        <a>
          <div className="h-48 bg-gray-100 mb-3 flex items-center justify-center overflow-hidden">
            <img src={p.image_url} alt={p.title} className="object-cover h-full w-full" />
          </div>
          <h3 className="text-lg font-semibold">{p.title}</h3>
          <div className="text-indigo-600 font-semibold mt-1">৳ {(p.price/100).toFixed(2)}</div>
        </a>
      </Link>
    </div>
  )
}""",

    "components/ProductCarousel.jsx": r"""import { useState } from 'react'

export default function ProductCarousel({ images = [] }) {
  const [idx, setIdx] = useState(0)
  if (!images.length) return null
  return (
    <div>
      <div className="h-64 bg-gray-100 flex items-center justify-center mb-2">
        <img src={images[idx]} alt="product" className="object-contain h-full" />
      </div>
      <div className="flex space-x-2">
        {images.map((src,i) => (
          <button key={i} onClick={() => setIdx(i)} className={`w-16 h-16 border ${i===idx ? 'ring-2 ring-indigo-600' : ''}`}>
            <img src={src} alt="" className="object-cover h-full w-full" />
          </button>
        ))}
      </div>
    </div>
  )
}""",

    "pages/index.js": r"""import useTranslation from 'next-translate/useTranslation'
import { useEffect, useState } from 'react'
import Slider from '../components/Slider'
import { supabase } from '../lib/supabaseClient'

export default function Home() {
  const { t, lang } = useTranslation('common')
  const [slides, setSlides] = useState([])

  useEffect(() => {
    async function load() {
      const { data } = await supabase.from('slider_items').select('*').eq('locale', lang || 'bn').order('created_at', { ascending: true })
      setSlides(data || [])
    }
    load()
  }, [lang])

  return (
    <div>
      <Slider items={slides} />
      <section className="text-center py-12">
        <h1 className="text-4xl font-bold mb-2">{t('home.welcome')}</h1>
        <p className="text-lg text-gray-700 mb-6">{t('home.tagline')}</p>
      </section>
    </div>
  )
}""",

    "pages/shop/index.js": r"""import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabaseClient'
import useTranslation from 'next-translate/useTranslation'
import ProductCard from '../../components/ProductCard'

export default function Shop() {
  const { t, lang } = useTranslation('common')
  const [products, setProducts] = useState([])
  const [q, setQ] = useState('')
  const [category, setCategory] = useState('')
  const [categories, setCategories] = useState([])
  const [page, setPage] = useState(1)
  const perPage = 12

  useEffect(() => {
    async function loadCategories() {
      const { data } = await supabase.from('categories').select('*')
      setCategories(data || [])
    }
    loadCategories()
  }, [])

  useEffect(() => {
    async function load() {
      // join products and product_translations for current locale
      const { data } = await supabase
        .from('product_translations')
        .select('*, products(price, currency, stock)')
        .eq('locale', lang || 'bn')
        .ilike('title', `%${q}%`)
        .order('id', { ascending: false })
      let items = data || []
      if (category) items = items.filter(i => i.category_id == category)
      // map to usable product object
      const mapped = items.map(i => ({
        id: i.product_id,
        title: i.title,
        description: i.description,
        slug: i.slug,
        image_url: i.image_url,
        price: i.products?.price || 0,
        currency: i.products?.currency || 'BDT',
        stock: i.products?.stock || 0
      }))
      setProducts(mapped)
      setPage(1)
    }
    load()
  }, [q, category, lang])

  const paged = useMemo(() => products.slice((page-1)*perPage, page*perPage), [products, page])

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">{t('nav.shop')}</h1>
        <div className="flex items-center space-x-2">
          <input value={q} onChange={e => setQ(e.target.value)} placeholder={t('shop.searchPlaceholder')} className="border px-3 py-2" />
        </div>
      </div>

      <div className="mb-4">
        <select value={category} onChange={e => setCategory(e.target.value)} className="border px-3 py-2">
          <option value="">{t('shop.allCategories')}</option>
          {categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
        </select>
      </div>

      <div className="grid md:grid-cols-3 gap-4">
        {paged.map(p => <ProductCard key={p.id} p={p} />)}
      </div>

      <div className="flex items-center justify-center mt-6 space-x-2">
        <button disabled={page===1} onClick={() => setPage(p => p-1)} className="px-3 py-1 border">{t('shop.prev')}</button>
        <div>{page} / {Math.max(1, Math.ceil(products.length / perPage))}</div>
        <button disabled={page*perPage >= products.length} onClick={() => setPage(p => p+1)} className="px-3 py-1 border">{t('shop.next')}</button>
      </div>
    </div>
  )
}""",

    "pages/shop/[slug].js": r"""import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabaseClient'
import useTranslation from 'next-translate/useTranslation'
import ProductCarousel from '../../components/ProductCarousel'
import { useCart } from '../../lib/cart'

export default function ProductDetail() {
  const router = useRouter()
  const { slug } = router.query
  const { t, lang } = useTranslation('common')
  const [product, setProduct] = useState(null)
  const { addItem } = useCart()
  const [qty, setQty] = useState(1)

  useEffect(() => {
    if (!slug) return
    async function load() {
      const { data } = await supabase
        .from('product_translations')
        .select('*, products(price, currency, stock)')
        .eq('slug', slug)
        .eq('locale', lang || 'bn')
        .single()
      if (!data) return setProduct(null)
      setProduct({
        id: data.product_id,
        title: data.title,
        description: data.description,
        slug: data.slug,
        image_url: data.image_url,
        images: [data.image_url],
        price: data.products?.price || 0,
        currency: data.products?.currency || 'BDT',
        stock: data.products?.stock || 0
      })
    }
    load()
  }, [slug, lang])

  if (product === null) return <div>{t('shop.notFound')}</div>
  if (!product) return <div>Loading…</div>

  return (
    <div className="grid md:grid-cols-2 gap-6">
      <ProductCarousel images={product.images} />
      <div>
        <h1 className="text-2xl font-bold mb-2">{product.title}</h1>
        <div className="text-indigo-600 font-semibold mb-4">৳ {(product.price/100).toFixed(2)}</div>
        <div className="mb-4 text-gray-700">{product.description}</div>
        <div className="flex items-center space-x-2 mb-4">
          <input type="number" min="1" max={product.stock} value={qty} onChange={e => setQty(Number(e.target.value))} className="w-20 border px-2 py-1" />
          <button onClick={() => addItem({ id: product.id, title: product.title, price: product.price, image_url: product.image_url }, qty)} className="bg-indigo-600 text-white px-4 py-2 rounded">
            {t('shop.addToCart')}
          </button>
        </div>
      </div>
    </div>
  )
}""",

    "pages/cart.js": r"""import useTranslation from 'next-translate/useTranslation'
import { useCart } from '../lib/cart'
import Link from 'next/link'

export default function CartPage() {
  const { t } = useTranslation('common')
  const { cart, updateQty, removeItem, total } = useCart()

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">{t('nav.cart')}</h1>
      {cart.items.length === 0 ? (
        <div>{t('cart.empty')}</div>
      ) : (
        <div>
          <div className="space-y-4">
            {cart.items.map(i => (
              <div key={i.productId} className="flex items-center justify-between border p-3">
                <div className="flex items-center space-x-3">
                  <img src={i.image} alt="" className="w-20 h-20 object-cover" />
                  <div>
                    <div className="font-semibold">{i.title}</div>
                    <div>৳ {(i.price/100).toFixed(2)}</div>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <input type="number" value={i.qty} min="1" onChange={e => updateQty(i.productId, Number(e.target.value))} className="w-20 border px-2 py-1" />
                  <button onClick={() => removeItem(i.productId)} className="text-red-600">{t('cart.remove')}</button>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-6 text-right">
            <div className="text-xl font-semibold">Total: ৳ {(total()/100).toFixed(2)}</div>
            <Link href="/checkout">
              <a className="inline-block mt-3 bg-indigo-600 text-white px-4 py-2 rounded">{t('cart.checkout')}</a>
            </Link>
          </div>
        </div>
      )}
    </div>
  )
}""",

    "pages/checkout.js": r"""import useTranslation from 'next-translate/useTranslation'
import { useCart } from '../lib/cart'
import { useRouter } from 'next/router'
import { useState } from 'react'

export default function Checkout() {
  const { t } = useTranslation('common')
  const { cart } = useCart()
  const router = useRouter()
  const [loading, setLoading] = useState(false)

  const handleCheckout = async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/stripe/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ items: cart.items })
      })
      const data = await res.json()
      if (data.sessionUrl) {
        window.location.href = data.sessionUrl
      } else {
        alert(data.error || 'Checkout failed')
      }
    } catch (err) {
      alert(err.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">{t('checkout.title')}</h1>
      <p className="mb-4">{t('checkout.note')}</p>
      <button onClick={handleCheckout} disabled={loading || cart.items.length===0} className="bg-indigo-600 text-white px-4 py-2 rounded">
        {loading ? t('checkout.processing') : t('checkout.payWithStripe')}
      </button>
    </div>
  )
}""",

    "pages/api/stripe/checkout.js": r"""import Stripe from 'stripe'
import { supabaseAdmin } from '../../../lib/supabaseAdmin'

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '', { apiVersion: '2022-11-15' })

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  if (!process.env.STRIPE_SECRET_KEY) return res.status(500).json({ error: 'Stripe secret key not configured on server' })

  const { items } = req.body
  if (!items || !items.length) return res.status(400).json({ error: 'No items' })

  try {
    // map items to line items. Here we assume price in cents/paisa in product.price.
    const line_items = items.map(it => ({
      price_data: {
        currency: 'bdt',
        product_data: { name: it.title },
        unit_amount: it.price
      },
      quantity: it.qty
    }))

    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items,
      mode: 'payment',
      success_url: `${process.env.NEXT_PUBLIC_BASE_URL}/checkout/success`,
      cancel_url: `${process.env.NEXT_PUBLIC_BASE_URL}/checkout/cancel`
    })

    return res.status(200).json({ sessionUrl: session.url })
  } catch (err) {
    console.error(err)
    return res.status(500).json({ error: err.message })
  }
}""",

    "pages/checkout/success.js": r"""import useTranslation from 'next-translate/useTranslation'
import Link from 'next/link'

export default function Success() {
  const { t } = useTranslation('common')
  return (
    <div className="text-center">
      <h1 className="text-2xl font-bold">{t('checkout.success')}</h1>
      <p className="mt-4">{t('checkout.thanks')}</p>
      <Link href="/"><a className="mt-4 inline-block text-indigo-600">{t('nav.home')}</a></Link>
    </div>
  )
}""",

    "pages/api/admin/products.js": r"""import supabaseAdmin from '../../../lib/supabaseAdmin'

export default async function handler(req, res) {
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return res.status(500).json({ error: 'SUPABASE_SERVICE_ROLE_KEY not configured' })
  }

  const { method } = req

  if (method === 'GET') {
    const { locale } = req.query
    let q = supabaseAdmin.from('product_translations').select('*, products(*)')
    if (locale) q = q.eq('locale', locale)
    const { data, error } = await q.order('id', { ascending: false })
    if (error) return res.status(500).json({ error: error.message })
    return res.status(200).json(data)
  }

  if (method === 'POST') {
    const { product, translation } = req.body
    // product: { price, sku, stock, currency }
    // translation: { locale, title, description, slug, image_url, category_id }
    const { data: prod, error: prodErr } = await supabaseAdmin.from('products').insert([product]).select().single()
    if (prodErr) return res.status(500).json({ error: prodErr.message })
    const { data: trans, error: transErr } = await supabaseAdmin.from('product_translations').insert([{ ...translation, product_id: prod.id }]).select().single()
    if (transErr) return res.status(500).json({ error: transErr.message })
    return res.status(201).json({ product: prod, translation: trans })
  }

  if (method === 'PUT') {
    const { id, product, translation } = req.body
    if (product) {
      const { data, error } = await supabaseAdmin.from('products').update(product).eq('id', id)
      if (error) return res.status(500).json({ error: error.message })
    }
    if (translation) {
      const { data, error } = await supabaseAdmin.from('product_translations').update(translation).eq('product_id', id).eq('locale', translation.locale)
      if (error) return res.status(500).json({ error: error.message })
    }
    return res.status(200).json({ ok: true })
  }

  if (method === 'DELETE') {
    const { id } = req.query
    const { error } = await supabaseAdmin.from('products').delete().eq('id', id)
    if (error) return res.status(500).json({ error: error.message })
    return res.status(200).json({ ok: true })
  }

  res.setHeader('Allow', ['GET','POST','PUT','DELETE'])
  res.status(405).end(`Method ${method} Not Allowed`)
}""",

    "pages/api/admin/upload.js": r"""import supabaseAdmin from '../../../lib/supabaseAdmin'

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) return res.status(500).json({ error: 'Service role not configured' })

  try {
    // Expect base64 file payload or multipart? We'll accept JSON with base64 and filename
    const { filename, fileBase64, bucket = 'products' } = req.body
    if (!filename || !fileBase64) return res.status(400).json({ error: 'Missing fields' })
    const buffer = Buffer.from(fileBase64, 'base64')
    const path = `${Date.now()}_${filename}`
    const { data, error } = await supabaseAdmin.storage.from(bucket).upload(path, buffer, { contentType: 'image/jpeg', upsert: false })
    if (error) return res.status(500).json({ error: error.message })
    const publicUrl = supabaseAdmin.storage.from(bucket).getPublicUrl(path).publicURL
    return res.status(200).json({ path, publicUrl })
  } catch (err) {
    return res.status(500).json({ error: err.message })
  }
}""",

    "pages/admin/products.js": r"""import { useEffect, useState } from 'react'
import useTranslation from 'next-translate/useTranslation'
import { supabase } from '../../lib/supabaseClient'

export default function AdminProducts() {
  const { t } = useTranslation('common')
  const [products, setProducts] = useState([])
  const [form, setForm] = useState({ price: 1000, sku: '', stock: 10, currency: 'BDT', locale: 'bn', title: '', description: '', slug: '', image_url: '', category_id: '' })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    async function load() {
      const res = await fetch('/api/admin/products?locale=bn')
      const data = await res.json()
      setProducts(data || [])
      setLoading(false)
    }
    load()
  }, [])

  const handleCreate = async (e) => {
    e.preventDefault()
    setSaving(true)
    const product = { price: Number(form.price), sku: form.sku, stock: Number(form.stock), currency: form.currency }
    const translation = { locale: form.locale, title: form.title, description: form.description, slug: form.slug, image_url: form.image_url, category_id: form.category_id ? Number(form.category_id) : null }
    const res = await fetch('/api/admin/products', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ product, translation }) })
    const data = await res.json()
    if (!res.ok) alert(data.error || 'Error')
    else setProducts(prev => [data.translation, ...prev])
    setSaving(false)
  }

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">{t('admin.products')}</h1>

      <form onSubmit={handleCreate} className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-6">
        <input placeholder="SKU" value={form.sku} onChange={e => setForm({ ...form, sku: e.target.value })} className="border px-3 py-2" />
        <input placeholder="Price (paisa)" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} className="border px-3 py-2" />
        <input placeholder="Stock" value={form.stock} onChange={e => setForm({ ...form, stock: e.target.value })} className="border px-3 py-2" />
        <input placeholder="Image URL" value={form.image_url} onChange={e => setForm({ ...form, image_url: e.target.value })} className="border px-3 py-2" />
        <input placeholder="Title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="border px-3 py-2 col-span-2" />
        <input placeholder="Slug" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} className="border px-3 py-2" />
        <select value={form.locale} onChange={e => setForm({ ...form, locale: e.target.value })} className="border px-3 py-2">
          <option value="bn">বাংলা</option>
          <option value="en">English</option>
        </select>
        <button type="submit" disabled={saving} className="bg-indigo-600 text-white px-4 py-2 rounded">{saving ? t('admin.saving') : t('admin.create')}</button>
        <textarea placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="border px-3 py-2 col-span-2" />
      </form>

      <div>
        {loading ? <div>Loading…</div> :
          <div className="grid md:grid-cols-3 gap-4">
            {products.map(p => (
              <div key={p.id} className="border p-3">
                <img src={p.image_url} alt="" className="h-40 w-full object-cover mb-2" />
                <div className="font-semibold">{p.title}</div>
                <div className="text-sm text-gray-600">{p.description}</div>
              </div>
            ))}
          </div>
        }
      </div>
    </div>
  )
}""",

    "pages/auth/signup.js": r"""import { useState } from 'react'
import { supabase } from '../../lib/supabaseClient'
import { useRouter } from 'next/router'
import useTranslation from 'next-translate/useTranslation'

export default function SignUp() {
  const { t } = useTranslation('common')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const router = useRouter()
  const [loading, setLoading] = useState(false)

  const handleSignup = async (e) => {
    e.preventDefault()
    setLoading(true)
    const { error } = await supabase.auth.signUp({ email, password })
    setLoading(false)
    if (error) return alert(error.message)
    alert(t('auth.checkEmail'))
    router.push('/')
  }

  return (
    <div className="max-w-md mx-auto">
      <h1 className="text-2xl font-bold mb-4">{t('auth.signup')}</h1>
      <form onSubmit={handleSignup} className="space-y-3">
        <input placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} className="w-full border px-3 py-2" />
        <input placeholder="Password" type="password" value={password} onChange={e => setPassword(e.target.value)} className="w-full border px-3 py-2" />
        <button className="bg-indigo-600 text-white px-4 py-2 rounded" disabled={loading}>{loading ? t('auth.processing') : t('auth.signup')}</button>
      </form>
    </div>
  )
}""",

    "pages/auth/login.js": r"""import { useState } from 'react'
import { supabase } from '../../lib/supabaseClient'
import { useRouter } from 'next/router'
import useTranslation from 'next-translate/useTranslation'

export default function Login() {
  const { t } = useTranslation('common')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const router = useRouter()
  const [loading, setLoading] = useState(false)

  const handleLogin = async (e) => {
    e.preventDefault()
    setLoading(true)
    const { error } = await supabase.auth.signInWithPassword({ email, password })
    setLoading(false)
    if (error) return alert(error.message)
    router.push('/admin/products')
  }

  return (
    <div className="max-w-md mx-auto">
      <h1 className="text-2xl font-bold mb-4">{t('auth.login')}</h1>
      <form onSubmit={handleLogin} className="space-y-3">
        <input placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} className="w-full border px-3 py-2" />
        <input placeholder="Password" type="password" value={password} onChange={e => setPassword(e.target.value)} className="w-full border px-3 py-2" />
        <button className="bg-indigo-600 text-white px-4 py-2 rounded" disabled={loading}>{loading ? t('auth.processing') : t('auth.login')}</button>
      </form>
    </div>
  )
}""",

    "pages/articles/index.js": r"""import useTranslation from 'next-translate/useTranslation'
import { supabase } from '../../lib/supabaseClient'
import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Articles() {
  const { t, lang } = useTranslation('common')
  const [articles, setArticles] = useState([])

  useEffect(() => {
    async function load() {
      const { data } = await supabase.from('articles').select('*').eq('locale', lang || 'bn').order('created_at', { ascending: false })
      setArticles(data || [])
    }
    load()
  }, [lang])

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">{t('nav.articles')}</h1>
      <div className="space-y-4">
        {articles.map(a => (
          <div key={a.id} className="border p-3 rounded">
            <Link href={`/articles/${a.slug}`}><a className="font-semibold">{a.title}</a></Link>
            <p className="text-gray-700">{a.excerpt}</p>
          </div>
        ))}
      </div>
    </div>
  )
}""",

    "pages/articles/[slug].js": r"""import { useRouter } from 'next/router'
import useTranslation from 'next-translate/useTranslation'
import { supabase } from '../../lib/supabaseClient'
import { useEffect, useState } from 'react'

export default function ArticleDetail() {
  const { t, lang } = useTranslation('common')
  const router = useRouter()
  const { slug } = router.query
  const [article, setArticle] = useState(null)

  useEffect(() => {
    if (!slug) return
    async function load() {
      const { data } = await supabase.from('articles').select('*').eq('slug', slug).eq('locale', lang || 'bn').single()
      setArticle(data || null)
    }
    load()
  }, [slug, lang])

  if (!article) return <div>{t('articles.notFound')}</div>
  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">{article.title}</h1>
      <div className="prose max-w-none" dangerouslySetInnerHTML={{ __html: article.body }} />
    </div>
  )
}""",

    "pages/quran.js": r"""import useTranslation from 'next-translate/useTranslation'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'
import Slider from '../components/Slider'

export default function QuranPage() {
  const { t, lang } = useTranslation('common')
  const [verses, setVerses] = useState([])

  useEffect(() => {
    async function load() {
      const { data } = await supabase.from('quran_verses').select('*').eq('locale', lang || 'bn').limit(20)
      setVerses(data || [])
    }
    load()
  }, [lang])

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">{t('nav.quran')}</h1>
      <Slider items={verses.map(v => ({ title: `S${v.surah}:A${v.ayah}`, subtitle: v.translation, image_url: '' }))} />
      <div className="mt-6 space-y-4">
        {verses.map(v => (
          <div key={v.id} className="border rounded p-3">
            <div className="text-xl font-semibold">{`S${v.surah}:A${v.ayah}`}</div>
            <div className="text-right text-2xl leading-relaxed">{v.arabic}</div>
            <div className="text-gray-700 mt-2">{v.translation}</div>
          </div>
        ))}
      </div>
    </div>
  )
}""",

    "pages/dowa.js": r"""import useTranslation from 'next-translate/useTranslation'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'

export default function DowaPage() {
  const { t, lang } = useTranslation('common')
  const [duas, setDuas] = useState([])

  useEffect(() => {
    async function fetchDuas() {
      const { data } = await supabase.from('duas').select('*').eq('locale', lang || 'bn')
      setDuas(data || [])
    }
    fetchDuas()
  }, [lang])

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">{t('nav.dua')}</h1>
      <div className="space-y-4">
        {duas.map(d => (
          <div key={d.id} className="border rounded p-3">
            <div className="font-semibold">{d.title}</div>
            <div className="text-right text-lg mt-2">{d.arabic}</div>
            <div className="mt-2 text-gray-700">{d.translation}</div>
          </div>
        ))}
      </div>
    </div>
  )
}""",

    "pages/hadith.js": r"""import useTranslation from 'next-translate/useTranslation'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'

export default function HadithPage() {
  const { t, lang } = useTranslation('common')
  const [hadiths, setHadiths] = useState([])

  useEffect(() => {
    async function fetchHadiths() {
      const { data } = await supabase.from('hadiths').select('*').eq('locale', lang || 'bn')
      setHadiths(data || [])
    }
    fetchHadiths()
  }, [lang])

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">{t('nav.hadith')}</h1>
      <div className="space-y-4">
        {hadiths.map(h => (
          <div key={h.id} className="border rounded p-3">
            <div className="font-semibold">{h.title}</div>
            <div className="mt-2 text-gray-700">{h.text}</div>
            <div className="mt-1 text-sm text-gray-500">{h.source}</div>
          </div>
        ))}
      </div>
    </div>
  )
}""",

    "public/locales/en/common.json": r"""{
  "siteTitle": "Return in Islam Foundation",
  "nav": {
    "home": "Home",
    "articles": "Articles",
    "donate": "Donate",
    "about": "About",
    "prayerTimes": "Prayer Times",
    "shop": "Shop",
    "quran": "Quran",
    "dua": "Dua",
    "hadith": "Hadith",
    "cart": "Cart",
    "admin": "Admin"
  },
  "home": {
    "welcome": "Welcome",
    "tagline": "Return of the soul"
  },
  "shop": {
    "searchPlaceholder": "Search products...",
    "allCategories": "All categories",
    "prev": "Prev",
    "next": "Next",
    "addToCart": "Add to cart",
    "notFound": "Product not found"
  },
  "cart": {
    "empty": "Your cart is empty",
    "remove": "Remove",
    "checkout": "Proceed to Checkout"
  },
  "checkout": {
    "title": "Checkout",
    "note": "You will be redirected to Stripe to complete payment.",
    "processing": "Processing…",
    "payWithStripe": "Pay with Stripe",
    "success": "Payment successful",
    "thanks": "Thank you for your support"
  },
  "auth": {
    "signup": "Sign up",
    "login": "Login",
    "processing": "Processing…",
    "checkEmail": "Check your email for confirmation"
  },
  "admin": {
    "products": "Products Management",
    "create": "Create",
    "saving": "Saving…"
  },
  "footer": {
    "copy": "© Return in Islam Foundation"
  },
  "articles": {
    "notFound": "Article not found"
  }
}""",

    "public/locales/bn/common.json": r"""{
  "siteTitle": "রিটার্ন ইন ইসলাম ফাউন্ডেশন",
  "nav": {
    "home": "হোম",
    "articles": "নিবন্ধ",
    "donate": "দান",
    "about": "আমাদের সম্পর্কে",
    "prayerTimes": "নামাজের সময়",
    "shop": "দোকান",
    "quran": "কোরআন",
    "dua": "দোয়া",
    "hadith": "হাদিস",
    "cart": "কার্ট",
    "admin": "অ্যাডমিন"
  },
  "home": {
    "welcome": "স্বাগতম",
    "tagline": "আত্মার ফিরে আসা"
  },
  "shop": {
    "searchPlaceholder": "পণ্য খুঁজুন...",
    "allCategories": "সমস্ত বিভাগ",
    "prev": "পূর্ব",
    "next": "পরবর্তী",
    "addToCart": "কার্টে যোগ করুন",
    "notFound": "পণ্য পাওয়া যায়নি"
  },
  "cart": {
    "empty": "আপনার কার্ট খালি",
    "remove": "অপসারণ",
    "checkout": "চেকআউটে যান"
  },
  "checkout": {
    "title": "কাস্টিং",
    "note": "আপনি পেমেন্ট সম্পন্ন করার জন্য Stripe-এ রিডাইরেক্ট হবেন।",
    "processing": "প্রক্রিয়াকরণ…",
    "payWithStripe": "Stripe দিয়ে পেমেন্ট",
    "success": "পেমেন্ট সফল",
    "thanks": "আপনার সমর্থনের জন্য ধন্যবাদ"
  },
  "auth": {
    "signup": "সাইন আপ",
    "login": "লগইন",
    "processing": "প্রক্রিয়াকরণ…",
    "checkEmail": "নিশ্চিতকরণ ইমেইল চেক করুন"
  },
  "admin": {
    "products": "পণ্যের পরিচালনা",
    "create": "তৈরি করুন",
    "saving": "সংরক্ষণ করা হচ্ছে…"
  },
  "footer": {
    "copy": "© রিটার্ন ইন ইসলাম ফাউন্ডেশন"
  },
  "articles": {
    "notFound": "নিবন্ধ পাওয়া যায়নি"
  }
}"""
}

def create_structure():
    print(f"Creating project in current directory...")
    
    # base_dir এখন "." (বর্তমান ডিরেক্টরি)
    if not os.path.exists(base_dir):
        # যদি বর্তমান ডিরেক্টরি না থাকে (যা সম্ভব না কারণ আপনি ভেতরেই আছেন), তখন তৈরি করবে
        os.makedirs(base_dir)

    for file_path, content in files.items():
        full_path = os.path.join(base_dir, file_path)
        # Create directories if needed
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        # Write file
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content.strip())
        print(f"Created: {file_path}")

    print("\n✅ Project structure created successfully!")
    print("Now run: npm install")

if __name__ == "__main__":
    create_structure()